spring:
  application:
    name: apipay
  datasource:
    url: jdbc:postgresql://localhost:5432/bills_to_pay
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

logging:
  level:
    com.robdig7x.apipay: DEBUG